package com.generator.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.generator.dao.Companys;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table COMPANYS.
*/
public class CompanysDao extends AbstractDao<Companys, Long> {

    public static final String TABLENAME = "COMPANYS";

    /**
     * Properties of entity Companys.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdCompanyDatabase = new Property(1, Integer.class, "idCompanyDatabase", false, "ID_COMPANY_DATABASE");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property ImageUrl = new Property(3, String.class, "imageUrl", false, "IMAGE_URL");
        public final static Property LastUpdate = new Property(4, String.class, "lastUpdate", false, "LAST_UPDATE");
        public final static Property FlagAct = new Property(5, Integer.class, "flagAct", false, "FLAG_ACT");
        public final static Property LogoUrl = new Property(6, String.class, "logoUrl", false, "LOGO_URL");
        public final static Property PathBanner = new Property(7, String.class, "pathBanner", false, "PATH_BANNER");
        public final static Property PathLogos = new Property(8, String.class, "pathLogos", false, "PATH_LOGOS");
        public final static Property IdCategory = new Property(9, Long.class, "idCategory", false, "ID_CATEGORY");
        public final static Property IdCompany = new Property(10, Long.class, "idCompany", false, "ID_COMPANY");
    };

    private DaoSession daoSession;


    public CompanysDao(DaoConfig config) {
        super(config);
    }
    
    public CompanysDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'COMPANYS' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'ID_COMPANY_DATABASE' INTEGER," + // 1: idCompanyDatabase
                "'NAME' TEXT," + // 2: name
                "'IMAGE_URL' TEXT," + // 3: imageUrl
                "'LAST_UPDATE' TEXT," + // 4: lastUpdate
                "'FLAG_ACT' INTEGER," + // 5: flagAct
                "'LOGO_URL' TEXT," + // 6: logoUrl
                "'PATH_BANNER' TEXT," + // 7: pathBanner
                "'PATH_LOGOS' TEXT," + // 8: pathLogos
                "'ID_CATEGORY' INTEGER," + // 9: idCategory
                "'ID_COMPANY' INTEGER);"); // 10: idCompany
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'COMPANYS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Companys entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer idCompanyDatabase = entity.getIdCompanyDatabase();
        if (idCompanyDatabase != null) {
            stmt.bindLong(2, idCompanyDatabase);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(4, imageUrl);
        }
 
        String lastUpdate = entity.getLastUpdate();
        if (lastUpdate != null) {
            stmt.bindString(5, lastUpdate);
        }
 
        Integer flagAct = entity.getFlagAct();
        if (flagAct != null) {
            stmt.bindLong(6, flagAct);
        }
 
        String logoUrl = entity.getLogoUrl();
        if (logoUrl != null) {
            stmt.bindString(7, logoUrl);
        }
 
        String pathBanner = entity.getPathBanner();
        if (pathBanner != null) {
            stmt.bindString(8, pathBanner);
        }
 
        String pathLogos = entity.getPathLogos();
        if (pathLogos != null) {
            stmt.bindString(9, pathLogos);
        }
 
        Long idCategory = entity.getIdCategory();
        if (idCategory != null) {
            stmt.bindLong(10, idCategory);
        }
    }

    @Override
    protected void attachEntity(Companys entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Companys readEntity(Cursor cursor, int offset) {
        Companys entity = new Companys( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // idCompanyDatabase
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // imageUrl
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // lastUpdate
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // flagAct
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // logoUrl
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // pathBanner
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // pathLogos
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9) // idCategory
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Companys entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdCompanyDatabase(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setImageUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLastUpdate(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFlagAct(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setLogoUrl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPathBanner(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPathLogos(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setIdCategory(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Companys entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Companys entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBrandsDao().getAllColumns());
            builder.append(" FROM COMPANYS T");
            builder.append(" LEFT JOIN BRANDS T0 ON T.'ID_COMPANY'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Companys loadCurrentDeep(Cursor cursor, boolean lock) {
        Companys entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Brands brands = loadCurrentOther(daoSession.getBrandsDao(), cursor, offset);
        entity.setBrands(brands);

        return entity;    
    }

    public Companys loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Companys> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Companys> list = new ArrayList<Companys>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Companys> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Companys> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
