package com.generator.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.generator.dao.PromotionsDao;
import com.generator.dao.BrandsDao;
import com.generator.dao.CompanysDao;
import com.generator.dao.CategoriesDao;
import com.generator.dao.LocationsDao;
import com.generator.dao.UsersDao;
import com.generator.dao.UserByBrandsDao;
import com.generator.dao.PersonDao;
import com.generator.dao.UserByPromotionsDao;
import com.generator.dao.MostUsefulPromotionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 21): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 21;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        PromotionsDao.createTable(db, ifNotExists);
        BrandsDao.createTable(db, ifNotExists);
        CompanysDao.createTable(db, ifNotExists);
        CategoriesDao.createTable(db, ifNotExists);
        LocationsDao.createTable(db, ifNotExists);
        UsersDao.createTable(db, ifNotExists);
        UserByBrandsDao.createTable(db, ifNotExists);
        PersonDao.createTable(db, ifNotExists);
        UserByPromotionsDao.createTable(db, ifNotExists);
        MostUsefulPromotionDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        PromotionsDao.dropTable(db, ifExists);
        BrandsDao.dropTable(db, ifExists);
        CompanysDao.dropTable(db, ifExists);
        CategoriesDao.dropTable(db, ifExists);
        LocationsDao.dropTable(db, ifExists);
        UsersDao.dropTable(db, ifExists);
        UserByBrandsDao.dropTable(db, ifExists);
        PersonDao.dropTable(db, ifExists);
        UserByPromotionsDao.dropTable(db, ifExists);
        MostUsefulPromotionDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(PromotionsDao.class);
        registerDaoClass(BrandsDao.class);
        registerDaoClass(CompanysDao.class);
        registerDaoClass(CategoriesDao.class);
        registerDaoClass(LocationsDao.class);
        registerDaoClass(UsersDao.class);
        registerDaoClass(UserByBrandsDao.class);
        registerDaoClass(PersonDao.class);
        registerDaoClass(UserByPromotionsDao.class);
        registerDaoClass(MostUsefulPromotionDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
