package com.generator.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MOST_USEFUL_PROMOTION.
 */
public class MostUsefulPromotion {

    private Long id;
    private Integer idMostUsefulPromotionDatabase;
    private String imageUrl;
    private String textPromotion;

    public MostUsefulPromotion() {
    }

    public MostUsefulPromotion(Long id) {
        this.id = id;
    }

    public MostUsefulPromotion(Long id, Integer idMostUsefulPromotionDatabase, String imageUrl, String textPromotion) {
        this.id = id;
        this.idMostUsefulPromotionDatabase = idMostUsefulPromotionDatabase;
        this.imageUrl = imageUrl;
        this.textPromotion = textPromotion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdMostUsefulPromotionDatabase() {
        return idMostUsefulPromotionDatabase;
    }

    public void setIdMostUsefulPromotionDatabase(Integer idMostUsefulPromotionDatabase) {
        this.idMostUsefulPromotionDatabase = idMostUsefulPromotionDatabase;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getTextPromotion() {
        return textPromotion;
    }

    public void setTextPromotion(String textPromotion) {
        this.textPromotion = textPromotion;
    }

}
